image: ubuntu:24.04

stages:
  - build
  - dockerize
  - test-deploy
  - prod-deploy

before_script:
  - cd ./webapp
  - apt update -qy
  - apt install -y lftp
  - apt install -y curl
  - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  - apt-get install -y nodejs
  - npm install -g pnpm
  - pnpm install --no-frozen-lockfile

build:
  stage: build
  script:
    - pwd
    - ls
    - pnpm build
  artifacts:
    paths:
      - build
    expire_in: 1 hour

dockerize_webapp:
  stage: dockerize
  image: docker:27.1.1
  services:
    - name: docker:27.1.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script: []
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker build -t "$DOCKERHUB_IMAGE:latest" -t "$DOCKERHUB_IMAGE:$CI_COMMIT_SHORT_SHA" webapp
    - docker push "$DOCKERHUB_IMAGE:latest"
    - docker push "$DOCKERHUB_IMAGE:$CI_COMMIT_SHORT_SHA"
  only:
    - main
    - master

.deploy_template: &deploy_template
  script:
    - pwd
    - ls
    - cd ./webapp/build
    - lftp -e "set ssl:verify-certificate no; open $FTP_HOSTNAME; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete . $DEPLOY_PATH; bye"
  dependencies:
    - build
  before_script:
    - apt update -qy
    - apt install -y lftp

# Deploy to test server automatically after build
test_deploy:
  stage: test-deploy
  variables:
    DEPLOY_PATH: ./preview-deployment/preview.azfunctionsperformance.apps.lucanoahcaprez.ch/
    FTP_HOSTNAME: $FTP_HOSTNAME
    FTP_USERNAME: $FTP_USERNAME
    FTP_PASSWORD: $FTP_PASSWORD
  <<: *deploy_template
  only:
    - branches
  except:
    - main
    - master

# Deploy to prod server only after manual approval
prod_deploy:
  stage: prod-deploy
  variables:
    DEPLOY_PATH: ./azfunctionsperformance.apps.lucanoahcaprez.ch/
    FTP_HOSTNAME: $FTP_HOSTNAME
    FTP_USERNAME: $FTP_USERNAME
    FTP_PASSWORD: $FTP_PASSWORD
  <<: *deploy_template
  only:
    - main
    - master
  allow_failure: false
